server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/joaocarlosjunior/config-server-teste-tecnico.git
          search-paths:
            - /src/main/resources/email-service