server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/joaocarlosjunior/desafio-tecnico-config-server.git
          clone-on-start: true
          search-paths:
            - email-service